[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.85
startup_mode = "Maximized"

[font]
size = 11.0

[general]
import = [ "/home/paskal/.config/alacritty/catppuccin-mocha.toml",]

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"
