import = [ "/home/pth/.config/alacritty/catppuccin/catppuccin-mocha.toml",]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.85
startup_mode = "Maximized"

[shell]
program = "/bin/zsh"

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
